[theme]
primaryColor = "#7B61FF"          # purple accent color
backgroundColor = "#fdfcff"       # very light purple background
secondaryBackgroundColor = "#f8f5ff"  # slightly darker background for boxes
textColor = "#262730"             # dark text
font = "sans serif"
borderColor = "lavender"
headingFontSizes = ["36px", "24px", "20px"]

[logger]
level = "info"

[server]
fileWatcherType = "poll"

